name: New CTF Challenge
description: File a CTF Challenge.
title: "[CHAL]: "
labels: ["challenge"]
body:
  - type: textarea
    id: description
    attributes:
      label: Challenge Description
      description: What is the challenge about?
      placeholder: Paste the challenge description here.
    validations:
      required: true
